# Основное меню (шапка)

[[main]]
  name   = "Главная"          # или убери name, если только иконка
  pageRef = "main"               # ссылка на главную
  weight = 10
  pre    = "sigma-icon"            # иконка домика перед текстом

[[main]]
 name   = "Обучение"
 pageRef = "training"
 weight = 20
 pre    = "list"        # иконка газеты/статей

[[main]]
  name   = "Консалтинг"
  pageRef = "posts"
  weight = 30
  pre    = "mug-hot"             # иконка человека

[[main]]
  name = "Сертификация"  # ОБЯЗАТЕЛЬНО укажи identifier, если нет name!
  pageRef = "certificates"
  weight     = 40
  pre        = "shield"       # иконка GitHub

[[main]]
  name   = "Контакты"
  pageRef = "contacts"
  pre    = "edit"
  weight = 100

[[subnavigation]]
  name = "Специализированные тренинги:"
  pageRef = "specialTraining"
  weight = 5
  pre = "list" 

[[subnavigation]]
  name = "Зелёный пояс для нефтяников"
  pageRef = "specialTraining/GBOill"
  weight = 10
  pre = "graduation-cap"  

[[subnavigation]]
  name = "Зелёный пояс Real Estate"
  pageRef = "specialTraining/GBRetail"
  weight = 20
  pre = "graduation-cap" 

[[footer]]
  name = "Контакты:"
  pageRef = "posts/contacts"
  weight = 50

[[footer]]
  name = "+7(977) 517-58-57"
  weight = 60
  pre = "phone"  

[[footer]]
  name = "g_buzov@mail.ru"
  weight = 70
  pre = "email" 
