# Основное меню (шапка)

[[main]]
  name   = "Главная"          # или убери name, если только иконка
  pageRef = "main"               # ссылка на главную
  weight = 10
  pre    = "sigma-icon"            # иконка домика перед текстом

[[main]]
 name   = "Обучение"
 pageRef = "training"
 weight = 20
 pre    = "list"        # иконка газеты/статей

[[main]]
 name   = "Курсы"
 parent = "Обучение"
 pageRef = "training"
 weight = 10
 pre    = "list"        # иконка газеты/статей

[[main]]
 name   = "Зеленый пояс"
 parent = "Обучение"
 pageRef  = "Зеленый пояс Lean Six Sigma"
 weight = 20
 pre    = "graduation-cap"        # иконка газеты/статей


[[main]]
  name   = "Консалтинг"
  pageRef = "posts"
  weight = 30
  pre    = "mug-hot"             # иконка человека

[[main]]
  name = "Сертификация"  # ОБЯЗАТЕЛЬНО укажи identifier, если нет name!
  pageRef = "certificates"
  weight     = 40
  pre        = "graduation-cap"       # иконка GitHub

[[main]]
  name   = "Контакты"
  pageRef = "contacts"
  pre    = "edit"
  weight = 100

[[subnavigation]]
  name   = "Публикации"
  pageRef = "posts"
  weight = 10
  pre    = "stack-overflow"       # иконка GitHub


